Allow enabling egress gateway feature
gardener/gardener-extension-networking-cilium pull request #102
Opened 2022-06-27 14:08 UTC by jastBytes

**How to categorize this PR?**
/area networking
/kind enhancement

**What this PR does / why we need it**:
Egress gateway feature is now supported in cilium. It allows users to redirect egress pod traffic through specific, gateway nodes.
To enable the feature kube-proxy must be disabled.

```
spec:
  kubernetes:
    kubeProxy:
      enabled: false
```
The feature can be enabled via:

```
spec:
  networking:
    providerConfig:
      apiVersion: cilium.networking.extensions.gardener.cloud/v1alpha1
      kind: NetworkConfig
      egressGateway:
         enabled: true
```

**Which issue(s) this PR fixes**:
Fixes #98

**Special notes for your reviewer**:

**Release note**:

```other operator
Egress gateway feature is now supported in cilium. It allows users to redirect egress pod traffic through specific, gateway nodes.
```

2022-06-27 14:27 UTC, christianhuening commented
@ScheererJ would be awesome if you could have a look whether this is feasible. We would need that feature exposed for configuration. 
Thanks a ton!

2022-06-28 08:55 UTC, DockToFuture requested changes
Please also add in `pkg/apis/cilium/types_network.go` 	`EgressGateway *bool` and run `make generate` afterwards. 
Can you please also add some comment/docu in https://github.com/gardener/gardener-extension-networking-cilium/blob/master/docs/usage-as-end-user.md.

2022-06-28 13:11 UTC, DockToFuture commented on pkg/apis/cilium/types_network.go
> +	// +optional
this line can be removed

2022-06-29 08:14 UTC, DockToFuture commented
Can you plead run `make generate` and add the generated files to the PR?

2022-06-29 09:13 UTC, DockToFuture commented on pkg/apis/cilium/types_network.go
> +	EgressGateway *bool
```suggestion
	// EgressGateway flag to be enabled or not
	EgressGateway *EgressGateway
```

// EgressGateway enablement for cilium
type EgressGateway struct {
	Enabled bool
}

2022-06-29 09:18 UTC, DockToFuture commented on pkg/apis/cilium/v1alpha1/types_network.go
> +	EgressGateway *bool `json:"egressGateway,omitempty"`
```suggestion
	EgressGateway *EgressGateway `json:"egressGateway,omitempty"`
```

and add 
```
// EgressGateway enablement for cilium
type EgressGateway struct {
	Enabled bool `json:"enabled"`
}
```

2022-06-29 09:24 UTC, DockToFuture commented on pkg/charts/utils.go
> +		globalConfig.EgressGateway.Enabled = *config.EgressGateway
```suggestion
		globalConfig.EgressGateway.Enabled = config.EgressGateway.Enabled
```

2022-06-29 11:57 UTC, DockToFuture commented
> Can you please run `make generate` and add the generated files to the PR?

Still needs to be done. :)

2022-06-29 12:45 UTC, jastBytes commented
`make generate` ran through just fine, but no changes. Any hint?

```
> Generate
Successfully generated controller registration at ../../example/controller-registration.yaml
Generating deepcopy funcs
Generating defaulters
Generating conversions
Generating deepcopy funcs
Generating defaulters
Generating conversions
I0629 14:44:09.768812   35224 main.go:127] parsing go packages in directory .
I0629 14:44:13.903833   35224 main.go:229] using package=.
I0629 14:44:13.915682   35224 main.go:165] written to ../../../../hack/api-reference/cilium.md
I0629 14:44:13.933826   35297 main.go:127] parsing go packages in directory .
I0629 14:44:25.345737   35297 main.go:229] using package=.
I0629 14:44:25.763154   35297 main.go:165] written to ../../../../hack/api-reference/config.md
```

2022-06-29 13:27 UTC, DockToFuture commented
There should be some changes in the generated files because of type changes made under `pkg/apis/cilium/*`. The printed output seems to be ok for the `make generate` cmd.

2022-07-11 06:27 UTC, DockToFuture commented
Hello @jastBytes, is this PR still relevant to you?

2022-07-11 07:21 UTC, jastBytes commented
Excuse me! I really forgot about this one. We found that we currently do not need this feature since the egress IP address is a single one for shoots at GCP. I still would like to give you access because maybe someone else profits and even maybe we run into the need for this in the future. As far as I understood for AWS there are different egress IP addresses for the same cluster per zone.

2022-07-11 07:57 UTC, DockToFuture commented
For gcp it must not necessarily be one static IP! But if you want to have one or more static IP addresses you could use the CloudNAT feature and manually assign the IP addresses to the CloudNAT and specify the min port size used per VM. See https://github.com/gardener/gardener-extension-provider-gcp/blob/master/docs/usage-as-end-user.md. With that you can assure at least that the used IP addresses remain static otherwise they might change.

2022-07-11 08:12 UTC, DockToFuture approved these changes
/lgtm

2022-07-11 08:22 UTC, merged