Induce component version using ldflags
gardener/gardener-extension-networking-cilium pull request #192
Opened 2023-06-09 05:22 UTC by shafeeqes

**How to categorize this PR?**

/area networking
/kind enhancement

**What this PR does / why we need it**:
Currently, it is hard to find the version of the `networking-calico` images.
This PR improves this by inducing the version using ldflags.
Version can be printed by using the `--version` flag.

Also we log the version during the starting of the component.

Also with this PR, docker images built by make docker-images are tagged and build with a version including the commit hash (exactly like the images built by the pipeline).

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:
Similar to https://github.com/gardener/gardener-extension-networking-calico/pull/266

**Release note**:

```other operator
NONE
```

2023-06-09 08:31 UTC, ScheererJ requested changes
Please also adapt the PR description and replace calico with cilium where necessary.

2023-06-09 08:31 UTC, ScheererJ commented on Makefile
> +LD_FLAGS := "-w $(shell $(REPO_ROOT)/vendor/github.com/gardener/gardener/hack/get-build-ld-flags.sh "" $(REPO_ROOT)/VERSION "$(EXTENSION_PREFIX)")"
Please align as before.

```suggestion
LD_FLAGS                    := "-w $(shell $(REPO_ROOT)/vendor/github.com/gardener/gardener/hack/get-build-ld-flags.sh "" $(REPO_ROOT)/VERSION "$(EXTENSION_PREFIX)")"
```

2023-06-09 08:31 UTC, ScheererJ commented on cmd/gardener-extension-networking-cilium/app/app.go
> +const Name = "gardener-extension-networking-calico"
Please correct the name.

```suggestion
const Name = "gardener-extension-networking-cilium"
```

2023-06-15 08:31 UTC, ScheererJ commented
/test pull-extension-networking-cilium-e2e-kind

2023-06-19 10:26 UTC, shafeeqes commented
@ScheererJ Can we merge this?

2023-06-19 11:31 UTC, merged