update pr template
gardener/gardener-extension-networking-cilium pull request #32
Opened 2020-11-10 12:16 UTC by DockToFuture

**What this PR does / why we need it**:
Update PR template

**Release note**:

```improvement operator
None
```

2020-11-10 12:41 UTC, rfranzke requested changes
Can you rather add such a file https://github.com/gardener/gardener-extension-networking-calico/blob/master/hack/update-github-templates.sh to stay up-to-date with the Gardener's changes?

2020-11-13 08:25 UTC, DockToFuture commented
Can we merge this?

2020-11-13 08:43 UTC, timebertt approved these changes

2020-11-13 09:05 UTC, rfranzke approved these changes
/lgtm

2020-11-13 09:05 UTC, merged