Drop support for Shoots with Kubernetes version <= 1.26
gardener/gardener-extension-networking-cilium pull request #431
Opened 2024-10-30 15:17 UTC by RadaBDimitrova

**How to categorize this PR?**

/area networking
/kind cleanup

**What this PR does / why we need it**:
 Cleanup code for versions <= 1.26

**Which issue(s) this PR fixes**:
Part of https://github.com/gardener/gardener/issues/10339

**Special notes for your reviewer**:

In draft until the gardener/gardener PR is merged and released.

**Release note**:

```other operator
`networking-cilium` no longer supports Shoots with Кubernetes version <= 1.26.
```

2025-03-05 09:19 UTC, DockToFuture approved these changes
/lgtm

2025-03-05 10:43 UTC, ialidzhikov commented
/assign

/hold
due to issue with the e2e test

2025-03-05 10:54 UTC, ialidzhikov requested changes

2025-03-05 10:54 UTC, ialidzhikov commented on charts/gardener-extension-admission-cilium/charts/runtime/templates/poddisruptionbudget.yaml
> +  unhealthyPodEvictionPolicy: AlwaysAllow
You could preserve the existing empty line at the end of the file.

2025-03-05 10:54 UTC, ialidzhikov commented on charts/internal/cilium/charts/operator/templates/poddisruptionbudget.yaml
> +  unhealthyPodEvictionPolicy: AlwaysAllow
You could preserve the existing empty line at the end of the file.

2025-03-05 10:54 UTC, ialidzhikov commented on test/e2e/common_test.go
> +				EnableStaticTokenKubeconfig: pointer.Bool(false),
You could remove the `enableStaticTokenKubeconfig`. It is deprecated and scheduled to be removed in Gardener v1.120. Ref https://github.com/gardener/gardener/blob/d839b336dfd7576f6c4aff67dc0981c4e20209b2/pkg/apis/core/v1beta1/types_shoot.go#L619-L624

2025-03-05 10:54 UTC, ialidzhikov commented on test/e2e/common_test.go
>  				Kubelet: &gardencorev1beta1.KubeletConfig{
You could remove the empty `kubeAPIServer` field at L63.

2025-03-25 09:13 UTC, shafeeqes commented on test/e2e/common_test.go
> +				Nodes:          pointer.String("10.10.0.0/16"),
```suggestion
				Nodes:          ptr.To("10.10.0.0/16"),
```

2025-03-31 14:47 UTC, ialidzhikov commented
/hold cancel
the failing e2e test seems to be fixed with https://github.com/gardener/gardener-extension-networking-cilium/pull/533

2025-03-31 14:54 UTC, axel7born commented
> /hold cancel the failing e2e test seems to be fixed with #533
@ialidzhikov  There is the problem you describe in https://github.com/gardener/gardener-extension-networking-cilium/issues/523 , that leads to failing tests as shoots don't get ready.

2025-04-01 06:52 UTC, axel7born commented
/test pull-extension-networking-cilium-e2e-kind

2025-04-01 07:18 UTC, ialidzhikov approved these changes
/lgtm

2025-04-01 08:21 UTC, merged